import type { TrainingPlanWeek } from '../../../types/planBuilder'
import { describe, expect, it } from 'vitest'

import { runAsyncPlanGeneration } from '../asyncGenerationLoop'
import { QUALITY_V2_CONTROL } from '../qualityCalibrationV2'
import { PRODUCTIVE_QUALITY_VERSION, reviewPlanQuality } from '../qualityReview'
import { makeRunInputForTest } from './helpers/asyncLoopTestFixtures'
import { buildPlanForTest, buildWeekForTest } from './helpers/qualityTestFixtures'

describe('PRODUCTIVE_QUALITY_VERSION contract', () => {
  it('keeps an unmarked legacy week on v1 regardless of the productive constant', () => {
    const week = buildWeekForTest({ generationMeta: { attempts: 1 } })
    expect(reviewPlanQuality(buildPlanForTest(), [week]).qualityVersion).toBe(1)
  })

  it('activates the exact quality version backed by the frozen calibration', () => {
    expect(QUALITY_V2_CONTROL.calibratedQualityVersion).toBe(2)
    expect(PRODUCTIVE_QUALITY_VERSION).toBe(2)
  })

  it('persists calibrated v2 on a week generated by the real loop', async () => {
    const { input, base } = makeRunInputForTest({ weekCount: 1 })
    const written: { status: string, qualityVersion?: 1 | 2 }[] = []
    const writer = {
      ...base,
      async putWeek(week: TrainingPlanWeek) {
        written.push({
          status: week.status,
          qualityVersion: week.generationMeta.qualityVersion,
        })
      },
    }

    await runAsyncPlanGeneration({ ...input, writer })

    const generated = written.find((week) => week.status === 'draft')
    expect(generated?.qualityVersion).toBe(2)
  })
})
