export const ROUTES = {
  HOME:             '/',
  FEATURES:         '/features',
  PRICING:          '/pricing',
  COACHES:          '/coaches',
  TERMS:            '/terms',
  PRIVACY:          '/privacy',
  HEALTH_DISCLAIMER: '/health-disclaimer',
  WHOOP_DISCLAIMER: '/whoop-disclaimer',
  WEEK:             '/week',
  DAY:              (date: string) => `/day/${date}`,
  CHAT:             '/chat',
  PLAN_BUILDER:     '/plan-builder',
  COMPETITION_PLAN: '/competition-plan',
  PLAN_BUILDER_V2: '/plans/builder',
  SETTINGS:         '/settings',
  IMPORT:           '/import',
  ONBOARDING:       '/onboarding',
  COACH:            '/coach',
  IOS_WELCOME_PREVIEW: '/preview/ios-welcome',
} as const
