export const ROUTES = {
  HOME:             '/',
  FEATURES:         '/features',
  PRICING:          '/pricing',
  WEEK:             '/week',
  DAY:              (date: string) => `/day/${date}`,
  CHAT:             '/chat',
  PLAN_BUILDER:     '/plan-builder',
  COMPETITION_PLAN: '/competition-plan',
  PLAN_BUILDER_V2: '/plans/builder',
  SETTINGS:         '/settings',
  IMPORT:           '/import',
  ONBOARDING:       '/onboarding',
  COACH:            '/coach',
} as const
