import type { SessionType, SessionTypeConfig } from '../types'

export const SESSION_TYPE_CONFIG: Record<SessionType, SessionTypeConfig> = {
  squash: {
    type: 'squash',
    label: 'Squash',
    bgClass: 'bg-brand/12',
    textClass: 'text-brand-light',
    borderClass: 'border-brand/25',
    dotClass: 'bg-brand',
    icon: 'Zap',
  },
  running: {
    type: 'running',
    label: 'Running',
    bgClass: 'bg-emerald-500/15',
    textClass: 'text-emerald-400',
    borderClass: 'border-emerald-500/30',
    dotClass: 'bg-emerald-400',
    icon: 'Wind',
  },
  cycling: {
    type: 'cycling',
    label: 'Ciclismo',
    bgClass: 'bg-sky-500/15',
    textClass: 'text-sky-400',
    borderClass: 'border-sky-500/30',
    dotClass: 'bg-sky-400',
    icon: 'Bike',
  },
  strength: {
    type: 'strength',
    label: 'Fuerza',
    bgClass: 'bg-amber-500/15',
    textClass: 'text-amber-400',
    borderClass: 'border-amber-500/30',
    dotClass: 'bg-amber-400',
    icon: 'Dumbbell',
  },
  mobility: {
    type: 'mobility',
    label: 'Movilidad',
    bgClass: 'bg-rose-500/15',
    textClass: 'text-rose-400',
    borderClass: 'border-rose-500/30',
    dotClass: 'bg-rose-400',
    icon: 'Orbit',
  },
  recovery: {
    type: 'recovery',
    label: 'Recuperación',
    bgClass: 'bg-teal-500/15',
    textClass: 'text-teal-400',
    borderClass: 'border-teal-500/30',
    dotClass: 'bg-teal-400',
    icon: 'Heart',
  },
  nutrition: {
    type: 'nutrition',
    label: 'Nutrición',
    bgClass: 'bg-yellow-500/10',
    textClass: 'text-yellow-300',
    borderClass: 'border-yellow-500/25',
    dotClass: 'bg-yellow-300',
    icon: 'Apple',
  },
}

export const SQUASH_SUBTYPE_LABELS: Record<string, string> = {
  control: 'Control',
  training: 'Entrenamiento',
  match: 'Partido',
  competitive: 'Competitivo',
  light: 'Suave',
}
