import type { ExerciseGroup } from '../../types'

export type ExerciseCategory = 'lower' | 'upper' | 'core' | 'full_body'
export type MovementPattern = 'squat' | 'hinge' | 'push' | 'pull' | 'rotation' | 'carry' | 'locomotion'
export type IntensityType = 'strength' | 'power' | 'hypertrophy' | 'stability' | 'recovery'
export type EquipmentType =
  | 'barbell'
  | 'dumbbell'
  | 'bodyweight'
  | 'machine'
  | 'cable'
  | 'kettlebell'
  | 'medball'
  | 'bands'
  | 'trap_bar'
  | 'trx'
  | 'box'
  | 'ladder'
  | 'plate'
  | 'stability_ball'
  | 'assault_bike'
  | 'air_treadmill'
export type ExperienceLevel = 'beginner' | 'intermediate' | 'advanced'
export type ExerciseRiskLevel = 'low' | 'medium' | 'high'
export type ExerciseFatigueCost = 'low' | 'medium' | 'high'
export type ExercisePhase = 'base' | 'build' | 'peak' | 'taper' | 'transition' | 'race'
export type ExerciseRotationGroup = 'A' | 'B' | 'C'
export type Exercise1RMReference = 'squat' | 'deadlift' | 'benchPress' | 'overheadPress'

export interface ExerciseDefinition {
  id: string
  name: string
  category: ExerciseCategory
  movement: MovementPattern
  intensityType: IntensityType
  equipment: EquipmentType[]
  unilateral?: boolean
  tags: string[]
  description: string
  aliases?: string[]
  difficulty?: ExperienceLevel
  sportsTransfer?: string[]
  squashTransfer?: string[]
  riskLevel?: ExerciseRiskLevel
  fatigueCost?: ExerciseFatigueCost
  has1RMReference?: Exercise1RMReference
  appropriateForPhases?: ExercisePhase[]
  blockRotationGroup?: ExerciseRotationGroup
}

export type StrengthExerciseRole = 'main_lift' | 'accessory' | 'trunk' | 'power'

const RAW_STRENGTH_EXERCISE_LIBRARY: ExerciseDefinition[] = [
  {
    id: 'back_squat',
    name: 'Sentadilla trasera con barra',
    category: 'lower',
    movement: 'squat',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'advanced', 'athletic_transfer', 'squash_specific'],
    description: 'Sentadilla bilateral con barra en la espalda. Patrón principal de fuerza de tren inferior y producción de fuerza.',
    aliases: ['Back squat', 'Sentadilla', 'Barbell back squat'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['force_production', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'front_squat',
    name: 'Sentadilla frontal',
    category: 'lower',
    movement: 'squat',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'athletic_transfer', 'squash_specific'],
    description: 'Sentadilla con barra apoyada en los hombros delante del cuello. Más demanda de tronco y énfasis en cuádriceps.',
    aliases: ['Sentadilla frontal', 'Barbell front squat'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['force_production', 'trunk_stiffness'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'goblet_squat',
    name: 'Sentadilla goblet',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'kettlebell'],
    tags: ['lower_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Sentadilla con mancuerna o kettlebell frente al pecho. Buena opción para volumen, técnica o sesiones en casa.',
    aliases: ['Goblet squat'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Sentadilla búlgara',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'gym', 'home_gym', 'squash_specific', 'lateral_strength'],
    description: 'Sentadilla a una pierna con el pie de atrás elevado. Fuerza unilateral, equilibrio y control de tronco.',
    aliases: ['Bulgarian split squat', 'Sentadilla bulgara'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['single_leg_strength', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'walking_lunge',
    name: 'Zancadas caminando',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'general_fitness', 'squash_specific'],
    description: 'Caminata dando zancadas alternas con mancuernas o barra. Trabajo unilateral con demanda de coordinación y estabilidad.',
    aliases: ['Walking lunge', 'Zancadas', 'Lunges'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['court_lunge_capacity', 'single_leg_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'romanian_deadlift',
    name: 'Peso muerto rumano',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['lower_strength', 'hinge', 'gym', 'athletic_transfer', 'squash_specific'],
    description: 'Bisagra de cadera con piernas semi-extendidas y barra cercana al cuerpo. Énfasis en isquios, glúteos y rigidez de tronco.',
    aliases: ['Romanian deadlift', 'RDL'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'cycling', 'squash'],
    squashTransfer: ['posterior_chain', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'deadlift',
    name: 'Peso muerto',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'advanced'],
    description: 'Bisagra bilateral pesada con barra desde el piso. Fuerza máxima y fuerza global.',
    aliases: ['Deadlift'],
    difficulty: 'advanced',
    sportsTransfer: ['strength'],
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Peso muerto con trap bar',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['trap_bar', 'barbell'],
    tags: ['lower_strength', 'gym', 'athletic_transfer', 'general_fitness', 'squash_specific'],
    description: 'Bisagra con barra hexagonal, técnicamente más simple que el peso muerto convencional. Buena alternativa cuando el peso muerto clásico carga mucho la zona lumbar.',
    aliases: ['Trap bar deadlift', 'Trap bar DL', 'Hex bar deadlift'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['force_production', 'posterior_chain'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'hip_thrust',
    name: 'Empuje de cadera',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'hypertrophy',
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    tags: ['lower_strength', 'glute_focus', 'gym', 'home_gym', 'athletic_transfer', 'squash_specific'],
    description: 'Empuje de cadera con espalda apoyada en banco y barra sobre la pelvis. Fuerza de glúteos con transferencia a sprint y salto.',
    aliases: ['Hip thrust'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['hip_extension', 'acceleration'],
    riskLevel: 'low',
    fatigueCost: 'medium',
  },
  {
    id: 'step_up',
    name: 'Subida al cajón',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'beginner_friendly', 'home_gym', 'athletic_transfer', 'squash_specific'],
    description: 'Subida unilateral a un cajón con mancuernas o peso corporal. Transferencia clara a escaleras, carrera y movimiento en cancha.',
    aliases: ['Step up', 'Step-up', 'Subida al cajon'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
    squashTransfer: ['single_leg_strength', 'court_lunge_capacity'],
    riskLevel: 'low',
    fatigueCost: 'medium',
  },
  {
    id: 'bench_press',
    name: 'Press banca',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['upper_strength', 'gym', 'compound'],
    description: 'Press horizontal con barra. Patrón principal de empuje superior.',
    aliases: ['Bench press'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['upper_body_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Press inclinado con mancuernas',
    category: 'upper',
    movement: 'push',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'home_gym'],
    description: 'Press inclinado a 30-45° con mancuernas. Más amigable con el hombro y sesgo de hipertrofia moderado.',
    aliases: ['Incline dumbbell press'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'overhead_press',
    name: 'Press sobre cabeza',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'gym', 'compound', 'athletic_transfer', 'squash_specific'],
    description: 'Press vertical con barra o mancuernas. Alta demanda de rigidez de tronco y control de hombro.',
    aliases: ['Overhead press', 'Press hombro', 'Press militar'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'push_press',
    name: 'Push press con impulso',
    category: 'upper',
    movement: 'push',
    intensityType: 'power',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'power', 'gym', 'advanced', 'athletic_transfer'],
    description: 'Press vertical explosivo usando piernas para iniciar el movimiento. Expresión de potencia.',
    aliases: ['Push press'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'pull_up',
    name: 'Dominada',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'compound', 'gym', 'home_gym', 'squash_specific'],
    description: 'Dominada con peso corporal, agarre supinado o prono. Patrón principal de tirón vertical.',
    aliases: ['Pull up', 'Pull-up', 'Dominadas'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['shoulder_resilience', 'upper_back_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'assisted_pull_up',
    name: 'Dominada asistida',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['machine', 'bands'],
    tags: ['upper_strength', 'beginner_friendly', 'gym', 'home_gym'],
    description: 'Dominada con asistencia de máquina o banda. Permite construir volumen de tirón cuando aún no salen libres.',
    aliases: ['Assisted pull up', 'Assisted pull-up'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'bent_over_row',
    name: 'Remo inclinado',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'gym', 'compound'],
    description: 'Remo horizontal con barra y tronco inclinado. Demanda fuerza de espalda alta y de tronco.',
    aliases: ['Bent over row'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'chest_supported_row',
    name: 'Remo con pecho apoyado',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'machine'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'beginner_friendly'],
    description: 'Remo con pecho apoyado en banco inclinado. Reduce la fatiga lumbar y aísla la espalda alta.',
    aliases: ['Chest supported row'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'lat_pulldown',
    name: 'Jalón al pecho',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['machine', 'cable'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'beginner_friendly'],
    description: 'Tirón vertical en polea hacia el pecho. Opción controlada para volumen y trabajo amigable con el hombro.',
    aliases: ['Lat pulldown'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'pallof_press',
    name: 'Press Pallof',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['cable', 'bands'],
    tags: ['core', 'stability', 'athletic_transfer', 'gym', 'home_gym', 'squash_specific', 'anti_rotation'],
    description: 'Empuje anti-rotacional con polea o banda lateral. Entrena bracing y transferencia de fuerza.',
    aliases: ['Pallof press', 'Anti-rotation press'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['anti_rotation', 'trunk_stiffness'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'dead_bug',
    name: 'Control de tronco dead bug',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'beginner_friendly', 'home_gym', 'anti_extension'],
    description: 'Control de tronco acostado boca arriba moviendo brazo y pierna contralateral. Énfasis en respiración y estabilidad pélvica.',
    aliases: ['Dead bug', 'Bicho muerto'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness', 'squash'],
    squashTransfer: ['pelvic_control', 'trunk_stiffness'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'plank',
    name: 'Plancha frontal',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'beginner_friendly', 'home_gym'],
    description: 'Plancha isométrica de tronco con dosificación simple. Glúteos y abdomen apretados.',
    aliases: ['Plank'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'side_plank',
    name: 'Plancha lateral',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'unilateral', 'home_gym', 'squash_specific', 'lateral_stability'],
    description: 'Plancha lateral en antebrazo para estabilidad lateral del tronco. Útil para corredores y deportes de raqueta.',
    aliases: ['Side plank'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
    squashTransfer: ['lateral_stability', 'anti_lateral_flexion'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'med_ball_rotational_throw',
    name: 'Lanzamiento rotacional con balón medicinal contra pared',
    category: 'core',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['core', 'power', 'athletic_transfer', 'gym'],
    description: 'Lanzamiento rotacional explosivo con balón medicinal contra una pared. Potencia rotacional con fuerte transferencia a deportes de raqueta.',
    aliases: ['Med ball rotational throw'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'cable_chop',
    name: 'Corte diagonal en polea',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['cable', 'bands'],
    tags: ['core', 'rotation', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Corte diagonal en polea de arriba hacia abajo. Transferencia rotacional controlada entre caderas y hombros.',
    aliases: ['Cable chop'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
  },
  {
    id: 'farmer_carry',
    name: 'Caminata del granjero',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['dumbbell', 'kettlebell'],
    tags: ['core', 'carry', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Caminata cargando mancuernas o kettlebells en cada mano. Agarre, rigidez de tronco e integridad de marcha.',
    aliases: ['Farmer carry'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash', 'cycling'],
  },
  {
    id: 'box_jump',
    name: 'Salto al cajón',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight', 'box'],
    tags: ['power', 'athletic_transfer', 'gym', 'squash_specific', 'jump_power'],
    description: 'Salto vertical sobre un cajón con intención explosiva. Aterriza suave en cuclillas; bajar caminando, no saltando.',
    aliases: ['Box jump', 'Salto al cajon'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
    squashTransfer: ['vertical_power', 'landing_quality'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'jump_squat',
    name: 'Sentadilla con salto',
    category: 'full_body',
    movement: 'squat',
    intensityType: 'power',
    equipment: ['bodyweight', 'dumbbell'],
    tags: ['power', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Sentadilla explosiva terminando en salto. Énfasis en velocidad de producción de fuerza.',
    aliases: ['Jump squat'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'med_ball_slam',
    name: 'Golpe al suelo con balón medicinal',
    category: 'full_body',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Lanzar el balón medicinal contra el suelo con fuerza desde arriba. Patrón explosivo de cuerpo entero con bajo costo excéntrico.',
    aliases: ['Med ball slam'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'rotational_med_ball_throw',
    name: 'Lanzamiento rotacional con balón medicinal',
    category: 'full_body',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Lanzamiento rotacional explosivo con balón medicinal contra la pared. Intención de transferencia deportiva.',
    aliases: ['Rotational med ball throw'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'kettlebell_swing',
    name: 'Swing con kettlebell',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['kettlebell'],
    tags: ['power', 'athletic_transfer', 'home_gym', 'gym'],
    description: 'Bisagra balística llevando la kettlebell hasta la altura del pecho. Velocidad de cadera y snap de cadena posterior.',
    aliases: ['Kettlebell swing'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'clean',
    name: 'Cargada',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'olympic_power', 'advanced', 'high_skill', 'athletic_transfer', 'squash_specific'],
    description: 'Patrón olímpico tirón-cachado. Potencia total con la barra desde el piso a los hombros. Movimiento avanzado; aprenderlo con un técnico antes de cargar.',
    aliases: ['Clean', 'Power clean'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['rate_of_force_development', 'explosive_start'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'clean_high_pull',
    name: 'Tirón alto de cargada',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'olympic_power', 'advanced', 'high_skill', 'athletic_transfer', 'squash_specific'],
    description: 'Variación olímpica explosiva sin la fase de cachado. Útil para potencia cuando la técnica del clean completo aún está en desarrollo.',
    aliases: ['Clean high pull', 'High pull', 'Clean pull alto'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['rate_of_force_development', 'posterior_chain_power'],
    riskLevel: 'high',
    fatigueCost: 'medium',
  },
  {
    id: 'split_jerk',
    name: 'Envión en tijera',
    category: 'full_body',
    movement: 'push',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'olympic_power', 'advanced', 'high_skill', 'athletic_transfer', 'squash_specific'],
    description: 'Envión olímpico explosivo con caída en tijera. Alta coordinación y estabilidad de hombro. Movimiento avanzado que requiere progresión técnica.',
    aliases: ['Split jerk', 'Jerk split', 'Envion split'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['split_stance_power', 'trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'barbell_jump_squat',
    name: 'Sentadilla con salto y barra',
    category: 'full_body',
    movement: 'squat',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'jump_power', 'advanced', 'athletic_transfer', 'squash_specific'],
    description: 'Sentadilla con barra terminando en salto. Intención explosiva con carga ligera (no más del 30% del back squat). Aterrizaje suave.',
    aliases: ['Barbell jump squat', 'Jump squat con barra', 'BB jump squat'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['vertical_power', 'rate_of_force_development'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'bb_reverse_lunge',
    name: 'Zancada inversa con barra',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['barbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'squash_specific', 'court_lunge'],
    description: 'Zancada hacia atrás con barra alta. Trabaja desaceleración, control de cadera y capacidad de lunge específica de squash.',
    aliases: ['Barbell reverse lunge', 'Reverse lunge con barra', 'Zancada atras con barra'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['court_lunge_capacity', 'deceleration', 'single_leg_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'bb_side_lunge',
    name: 'Zancada lateral con barra',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['barbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'squash_specific', 'lateral_strength', 'court_lunge'],
    description: 'Zancada lateral con barra. Fuerza en plano frontal y posiciones de pelota ancha en cancha de squash.',
    aliases: ['BB side lunges', 'Barbell side lunge', 'Lateral lunge con barra', 'Zancada lateral con barra'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['lateral_strength', 'court_lunge_capacity', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'single_leg_hip_thrust',
    name: 'Empuje de cadera a una pierna',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight', 'dumbbell', 'barbell'],
    unilateral: true,
    tags: ['lower_strength', 'glute_focus', 'unilateral', 'athletic_transfer', 'squash_specific'],
    description: 'Empuje de cadera unilateral con espalda en banco. Fuerza de glúteos con menor costo lumbar que el bilateral.',
    aliases: ['Single leg hip thrust', 'SL hip thrust', 'Hip thrust una pierna'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['hip_extension', 'single_leg_strength'],
    riskLevel: 'low',
    fatigueCost: 'medium',
  },
  {
    id: 'z_press',
    name: 'Press Z',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'trunk_stability', 'gym', 'athletic_transfer', 'squash_specific'],
    description: 'Press vertical sentado en el piso con piernas extendidas. Expone limitaciones de control de tronco y hombro overhead.',
    aliases: ['Z Press', 'Z press'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'mixed_grip_pull_up',
    name: 'Dominada con agarre mixto',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'compound', 'gym', 'squash_specific'],
    description: 'Dominada con una mano supinada y otra prona. Reta agarre y control de hombro de forma asimétrica. Alterna el agarre entre series.',
    aliases: ['Mixed grip pull up', 'Mixed grip pull-up', 'Dominada agarre mixto'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['grip_strength', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'weighted_pull_up',
    name: 'Dominada lastrada',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight', 'plate', 'dumbbell'],
    tags: ['upper_strength', 'compound', 'gym', 'advanced', 'squash_specific'],
    description: 'Dominada con lastre (cinturón o chaleco). Fuerza máxima de tirón vertical.',
    aliases: ['Weighted pull up', 'Weighted pull-up'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['grip_strength', 'upper_back_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'trx_inverted_row',
    name: 'Remo invertido en TRX',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['trx', 'bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'squash_specific'],
    description: 'Remo en suspensión con TRX. Dificultad escalable según ángulo del cuerpo. El cuerpo va recto como una tabla durante todo el movimiento.',
    aliases: ['TRX inverted row', 'TRX row', 'Remo invertido TRX'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['upper_back_strength', 'shoulder_resilience'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'half_kneeling_row',
    name: 'Remo medio arrodillado',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['cable', 'bands', 'dumbbell'],
    tags: ['upper_strength', 'anti_rotation', 'athletic_transfer', 'squash_specific'],
    description: 'Remo en polea desde posición medio arrodillado. Une fuerza de espalda alta con control pélvico y de tronco. La cadera no debe rotar al tirar.',
    aliases: ['Half kneeling row', '1:2 Kneeling Row', '1/2 Kneeling Row', 'Half-kneeling row'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['anti_rotation', 'upper_back_strength'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'barbell_single_leg_inverted_row',
    name: 'Remo invertido con barra a una pierna',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['barbell', 'bodyweight'],
    unilateral: true,
    tags: ['upper_strength', 'core', 'athletic_transfer', 'squash_specific'],
    description: 'Remo invertido bajo una barra apoyando solo un pie. Suma demanda de cadena posterior y control de tronco.',
    aliases: ['Barbell single leg inverted row', 'BB single leg inverted row', 'Single leg inverted row'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['upper_back_strength', 'trunk_stiffness'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'broad_jump',
    name: 'Salto horizontal',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    tags: ['power', 'jump_power', 'athletic_transfer', 'squash_specific'],
    description: 'Salto horizontal a máxima distancia con dos pies. Intención de aceleración y calidad de aterrizaje. Aterriza suave en cuclillas.',
    aliases: ['Broad jump'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['horizontal_power', 'landing_quality'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'single_leg_broad_jump',
    name: 'Salto horizontal a una pierna',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    unilateral: true,
    tags: ['power', 'jump_power', 'unilateral', 'advanced', 'squash_specific'],
    description: 'Salto horizontal unilateral con aterrizaje controlado en una pierna. Potencia unilateral con alta demanda de estabilidad en la recepción.',
    aliases: ['Single leg broad jump', 'SL broad jump', 'Salto horizontal una pierna'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['single_leg_power', 'landing_quality'],
    riskLevel: 'high',
    fatigueCost: 'medium',
  },
  {
    id: 'drop_jump',
    name: 'Salto reactivo desde cajón',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['box', 'bodyweight'],
    tags: ['power', 'reactive_stiffness', 'advanced', 'high_impact', 'squash_specific'],
    description: 'Caer desde un cajón bajo y rebotar inmediatamente hacia arriba. Énfasis en rigidez reactiva y contacto con el piso menor a 0.25 s. Cajón bajo (20-30 cm).',
    aliases: ['Drop jump', 'Salto reactivo desde cajon'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['reactive_stiffness', 'split_step_quality'],
    riskLevel: 'high',
    fatigueCost: 'medium',
  },
  {
    id: 'depth_jump',
    name: 'Salto profundo',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['box', 'bodyweight'],
    tags: ['power', 'reactive_stiffness', 'advanced', 'high_impact', 'squash_specific'],
    description: 'Caer desde un cajón y rebotar hacia un salto vertical alto. Pliométrico de alta intensidad solo para atletas avanzados. Volumen muy bajo (5-10 reps).',
    aliases: ['Depth jump'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['reactive_stiffness', 'explosive_reacceleration'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'half_kneeling_lateral_jump',
    name: 'Salto lateral medio arrodillado',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    unilateral: true,
    tags: ['power', 'lateral_power', 'athletic_transfer', 'squash_specific'],
    description: 'Salto lateral partiendo desde posición de medio arrodillado. Snap de cadera y potencia en plano frontal.',
    aliases: ['Half kneeling lateral jump', 'Half-kneeling lateral jump'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['lateral_power', 'court_reacceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'lateral_skater_jumps',
    name: 'Saltos laterales de patinador',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    unilateral: true,
    tags: ['power', 'lateral_power', 'athletic_transfer', 'squash_specific'],
    description: 'Saltos laterales alternando de pie en pie. Potencia lateral, desaceleración y reaceleración. Aterriza absorbiendo y empuja para el siguiente salto.',
    aliases: ['Lateral skater jumps', 'Skater jumps', 'Saltos patinador'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['lateral_power', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'alternating_step_up_jump',
    name: 'Subida al cajón con salto alternado',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['box', 'bodyweight'],
    unilateral: true,
    tags: ['power', 'jump_power', 'athletic_transfer', 'squash_specific'],
    description: 'Step-up explosivo cambiando de pierna en el aire. Potencia unilateral con ritmo. El cambio de pierna ocurre en el aire.',
    aliases: ['Alternating step up jump', 'Step up jump alternado'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['single_leg_power', 'court_reacceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'pogo_jumps',
    name: 'Saltos pogo',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    tags: ['power', 'reactive_stiffness', 'athletic_transfer', 'squash_specific'],
    description: 'Saltos verticales bajos seguidos manteniendo tobillo rígido. Elasticidad de tobillo para split-step y footwork. Mínima flexión de rodilla; rebote con tobillo.',
    aliases: ['Pogo jumps', 'Pogos'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['reactive_stiffness', 'split_step_quality'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_front_1',
    name: 'Escalera frontal – dos pies por cuadro',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Avanza por la escalera entrando ambos pies dentro de cada cuadro antes de pasar al siguiente. Mantén ritmo constante y postura erguida.',
    aliases: ['Escalera bipodal frente 1', 'Ladder bipodal front 1'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'split_step_quality'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_front_2',
    name: 'Escalera frontal – in-in-out-out',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Entra dos pies dentro del primer cuadro, sale dos pies afuera al lado del segundo, vuelve a entrar dos pies y avanza. El patrón in-in-out-out entrena cadencia y separación de pies.',
    aliases: ['Escalera bipodal frente 2', 'Ladder bipodal front 2'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'split_step_quality'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_front_3',
    name: 'Escalera frontal – salto bipodal por cuadro',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Salta con los dos pies juntos cuadro por cuadro avanzando hacia adelante. Aterriza suave y rebota al siguiente cuadro. Foco en elasticidad de tobillo, no en altura.',
    aliases: ['Escalera bipodal frente 3', 'Ladder bipodal front 3'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'split_step_quality'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_coordinativo_front_2',
    name: 'Escalera frontal – un pie por cuadro',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Avanza por la escalera apoyando un solo pie por cuadro, alternando pie derecho e izquierdo. Foco en rapidez y precisión de apoyo.',
    aliases: ['Escalera coordinativo frente 2', 'Ladder coordination front 2'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'court_reacceleration'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_coordinativo_front_4',
    name: 'Escalera frontal – Icky shuffle',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Patrón Icky shuffle: dentro-dentro-fuera avanzando en diagonal cruzada. Pies activos, cadera abierta. Cuando se domine, súbele velocidad sin perder precisión.',
    aliases: ['Escalera coordinativo frente 4', 'Ladder coordination front 4'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'court_reacceleration'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_lateral_1',
    name: 'Escalera lateral – dos pies por cuadro',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'lateral_power', 'squash_specific', 'beginner_friendly'],
    description: 'Avanza de costado entrando los dos pies en cada cuadro antes de pasar al siguiente. Hombros al frente, cadera baja. Repite en ambas direcciones para no generar asimetría.',
    aliases: ['Escalera bipodal lateralizacion 1', 'Ladder bipodal lateral 1'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'lateral_movement'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_lateral_3',
    name: 'Escalera lateral – shuffle in-in-out',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'lateral_power', 'squash_specific', 'beginner_friendly'],
    description: 'De costado: entra dos pies en el cuadro, sale un pie afuera, vuelve a entrar y avanza. Ritmo de shuffle lateral. Mantén el centro de gravedad bajo y los pies rápidos.',
    aliases: ['Escalera bipodal lateralizacion 3', 'Ladder bipodal lateral 3'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'lateral_movement'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'assault_bike_30_30',
    name: 'Bici de asalto 30/30',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['assault_bike', 'machine'],
    tags: ['cardio_specific', 'court_conditioning', 'repeat_sprint', 'squash_specific'],
    description: 'Bloque final de repeat sprint en bici de asalto: 30 segundos fuerte / 30 segundos suave durante 4 minutos. Mantén potencia alta sin perder postura ni respiración.',
    aliases: ['Bici de asalto', 'Assault bike', 'Air bike', 'Bicicleta de asalto', 'Bici assault 30/30'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['repeat_sprint_capacity', 'short_point_recovery'],
    riskLevel: 'low',
    fatigueCost: 'high',
  },
  {
    id: 'air_treadmill_20_20',
    name: 'Trotadora de aire 20/20',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['air_treadmill', 'machine'],
    tags: ['cardio_specific', 'court_conditioning', 'repeat_sprint', 'squash_specific'],
    description: 'Bloque final en trotadora curva/de aire: 20 segundos fuerte / 20 segundos suave durante 4 minutos. Mejor para aceleraciones cortas y mecánica rápida sin alargar demasiado el esfuerzo.',
    aliases: ['Trotadora de aire', 'Air runner', 'Curved treadmill', 'Trotadora curva', 'Cinta curva', 'Air treadmill'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['repeat_sprint_capacity', 'short_point_recovery', 'acceleration'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'copenhagen_side_plank',
    name: 'Plancha lateral Copenhagen',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight', 'box'],
    unilateral: true,
    tags: ['core', 'stability', 'lateral_stability', 'adductor_strength', 'squash_specific'],
    description: 'Variación de plancha lateral con pierna superior apoyada en banco. Énfasis en fuerza de aductores y estabilidad lateral. Empieza apoyando la rodilla antes de pasar al tobillo.',
    aliases: ['Copenhagen side plank', 'Copenhagen plank', 'Plancha Copenhagen'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['adductor_strength', 'lateral_stability'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'side_plank_plate_press',
    name: 'Plancha lateral con press de disco',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['plate', 'bodyweight'],
    unilateral: true,
    tags: ['core', 'stability', 'lateral_stability', 'anti_rotation', 'squash_specific'],
    description: 'Plancha lateral sosteniendo y empujando un disco hacia arriba. Reta estabilidad lateral y control anti-rotacional. El disco va recto al techo; la cadera no cae.',
    aliases: ['Side plank + plate press', 'Side plank plate press'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['lateral_stability', 'anti_rotation'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'stability_ball_front_plank',
    name: 'Plancha frontal en fitball',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['stability_ball', 'bodyweight'],
    tags: ['core', 'stability', 'anti_extension', 'squash_specific'],
    description: 'Plancha con antebrazos sobre fitball. Anti-extensión y control hombro-tronco. Pequeños círculos con la pelota aumentan la dificultad.',
    aliases: ['Stability ball front plank', 'Swiss ball plank', 'Plancha frontal fitball'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'lateral_band_walk',
    name: 'Caminata lateral con banda',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['bands'],
    tags: ['lower_strength', 'stability', 'lateral_strength', 'beginner_friendly', 'squash_specific'],
    description: 'Pasos laterales con banda en tobillos o rodillas. Activación de glúteo medio y tracking de rodilla. Pasos cortos; tronco quieto.',
    aliases: ['Lateral band walk', 'Monster walk lateral'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['lateral_stability', 'hip_control'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'bird_dog_renegade_row',
    name: 'Remo renegado bird dog',
    category: 'core',
    movement: 'pull',
    intensityType: 'stability',
    equipment: ['dumbbell'],
    unilateral: true,
    tags: ['core', 'upper_strength', 'anti_rotation', 'squash_specific'],
    description: 'Remo en posición de plancha con mancuernas elevando la mancuerna y la pierna contralateral. Anti-rotación y control de hombro. La cadera no rota al tirar.',
    aliases: ['Bird dog renegade row', 'Bird-dog renegade row'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['anti_rotation', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'half_kneeling_diagonal_plate_chop',
    name: 'Corte diagonal con disco medio arrodillado',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['plate'],
    tags: ['core', 'rotation', 'anti_rotation', 'athletic_transfer', 'squash_specific'],
    description: 'Corte diagonal con un disco desde posición medio arrodillado. Transferencia rotacional controlada. Pies y cadera fijos; el giro nace del tronco.',
    aliases: ['Half kneeling diagonal plate chop', 'Half-kneeling plate chop'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['anti_rotation', 'controlled_rotation'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'bodyweight_squat',
    name: 'Sentadilla con peso corporal',
    category: 'lower',
    movement: 'squat',
    intensityType: 'recovery',
    equipment: ['bodyweight'],
    tags: ['beginner_friendly', 'home_gym', 'general_fitness', 'recovery'],
    description: 'Sentadilla sin carga externa. Buena opción para preparación de tejidos, recuperación o nivel inicial.',
    aliases: ['Bodyweight squat'],
    difficulty: 'beginner',
    sportsTransfer: ['general_fitness'],
  },
  {
    id: 'push_up',
    name: 'Flexión de brazos',
    category: 'upper',
    movement: 'push',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Flexión con peso corporal. Empuje horizontal accesible para fuerza y volumen.',
    aliases: ['Push up', 'Push-up'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'glute_bridge',
    name: 'Puente de glúteo',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'recovery',
    equipment: ['bodyweight', 'bands', 'dumbbell'],
    tags: ['beginner_friendly', 'home_gym', 'recovery', 'athletic_transfer'],
    description: 'Puente de glúteo en suelo con peso corporal, banda o mancuerna. Activación y recuperación. Termina con cadera bien extendida sin sobreextender la lumbar.',
    aliases: ['Glute bridge'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'band_row',
    name: 'Remo con banda',
    category: 'upper',
    movement: 'pull',
    intensityType: 'recovery',
    equipment: ['bands'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'recovery'],
    description: 'Remo horizontal con banda elástica. Opción simple de tirón para recuperación o casa.',
    aliases: ['Band row'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'split_squat',
    name: 'Sentadilla en zancada',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight', 'dumbbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'beginner_friendly', 'home_gym'],
    description: 'Sentadilla a una pierna en posición de zancada estática, sin moverse del lugar. Patrón unilateral accesible con bajo setup.',
    aliases: ['Split squat'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'inverted_row',
    name: 'Remo invertido',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Tirón horizontal con peso corporal bajo una barra. Dificultad escalable según ángulo del cuerpo.',
    aliases: ['Inverted row'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
]

const EXERCISE_1RM_REFERENCES: Partial<Record<string, Exercise1RMReference>> = {
  back_squat: 'squat',
  front_squat: 'squat',
  goblet_squat: 'squat',
  deadlift: 'deadlift',
  romanian_deadlift: 'deadlift',
  trap_bar_deadlift: 'deadlift',
  bench_press: 'benchPress',
  incline_dumbbell_press: 'benchPress',
  overhead_press: 'overheadPress',
  push_press: 'overheadPress',
  z_press: 'overheadPress',
}

const EXERCISE_ROTATION_GROUPS: Partial<Record<string, ExerciseRotationGroup>> = {
  back_squat: 'A',
  deadlift: 'A',
  bench_press: 'A',
  overhead_press: 'A',
  pull_up: 'A',
  front_squat: 'B',
  romanian_deadlift: 'B',
  incline_dumbbell_press: 'B',
  push_press: 'B',
  bent_over_row: 'B',
  bulgarian_split_squat: 'C',
  hip_thrust: 'C',
  z_press: 'C',
  chin_up: 'C',
  trx_inverted_row: 'C',
}

function inferAppropriateForPhases(exercise: ExerciseDefinition): ExercisePhase[] {
  if (exercise.intensityType === 'strength') return ['base', 'build', 'peak']
  if (exercise.intensityType === 'power') return ['build', 'peak']
  if (exercise.intensityType === 'hypertrophy') return ['base', 'build']
  if (exercise.intensityType === 'stability') return ['base', 'build', 'peak', 'taper']
  if (exercise.intensityType === 'recovery') return ['base', 'taper', 'transition', 'race']
  return ['base', 'build']
}

function withExercisePhase2Metadata(exercise: ExerciseDefinition): ExerciseDefinition {
  return {
    ...exercise,
    has1RMReference: exercise.has1RMReference ?? EXERCISE_1RM_REFERENCES[exercise.id],
    appropriateForPhases: exercise.appropriateForPhases ?? inferAppropriateForPhases(exercise),
    blockRotationGroup: exercise.blockRotationGroup ?? EXERCISE_ROTATION_GROUPS[exercise.id],
  }
}

export const STRENGTH_EXERCISE_LIBRARY: ExerciseDefinition[] = RAW_STRENGTH_EXERCISE_LIBRARY.map(withExercisePhase2Metadata)

export function getStrengthExerciseRole(definition: ExerciseDefinition, index = 0): StrengthExerciseRole {
  if (definition.category === 'core') return 'trunk'
  if (definition.intensityType === 'power') return 'power'
  return index === 0 ? 'main_lift' : 'accessory'
}

export function normalizeStrengthExerciseKey(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
}

export function findStrengthExerciseByName(name: string): ExerciseDefinition | undefined {
  const normalized = normalizeStrengthExerciseKey(name)

  const exact = STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    normalizeStrengthExerciseKey(exercise.name) === normalized ||
    normalizeStrengthExerciseKey(exercise.id) === normalized,
  )
  if (exact) return exact

  const aliasExact = STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    exercise.aliases?.some((alias) => normalizeStrengthExerciseKey(alias) === normalized),
  )
  if (aliasExact) return aliasExact

  const aliasMap: Record<string, string> = {
    sentadilla: 'back_squat',
    sentadilla_frontal: 'front_squat',
    press_banca: 'bench_press',
    press_z: 'z_press',
    press_hombro: 'overhead_press',
    press_militar: 'overhead_press',
    remo_con_barra: 'bent_over_row',
    dominadas: 'pull_up',
    dominada_lastrada: 'weighted_pull_up',
    dominada_agarre_mixto: 'mixed_grip_pull_up',
    dominadas_asistidas: 'assisted_pull_up',
    peso_muerto: 'deadlift',
    peso_muerto_trap_bar: 'trap_bar_deadlift',
    peso_muerto_rumano: 'romanian_deadlift',
    rdl: 'romanian_deadlift',
    zancadas: 'walking_lunge',
    zancada_lateral_con_barra: 'bb_side_lunge',
    zancada_atras_con_barra: 'bb_reverse_lunge',
    core_rotacional: 'cable_chop',
    plancha: 'plank',
    plancha_lateral: 'side_plank',
    plancha_copenhagen: 'copenhagen_side_plank',
    puente_gluteo: 'glute_bridge',
    salto_al_cajon: 'box_jump',
    salto_horizontal: 'broad_jump',
    saltos_pogo: 'pogo_jumps',
  }

  const aliasId = aliasMap[normalized]
  if (aliasId) {
    return STRENGTH_EXERCISE_LIBRARY.find((exercise) => exercise.id === aliasId)
  }

  return STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    normalized.includes(normalizeStrengthExerciseKey(exercise.name)) ||
    normalizeStrengthExerciseKey(exercise.name).includes(normalized) ||
    exercise.aliases?.some((alias) =>
      normalized.includes(normalizeStrengthExerciseKey(alias)) ||
      normalizeStrengthExerciseKey(alias).includes(normalized),
    ),
  )
}

export function getExerciseGroupForDefinition(exercise: ExerciseDefinition): ExerciseGroup {
  if (
    exercise.equipment.includes('ladder') ||
    exercise.equipment.includes('assault_bike') ||
    exercise.equipment.includes('air_treadmill') ||
    exercise.tags.includes('court_footwork') ||
    exercise.tags.includes('court_conditioning') ||
    exercise.tags.includes('cardio_specific')
  ) return 'cardio'
  if (exercise.tags.includes('olympic_power')) return 'olympic'
  if (exercise.category === 'core') return 'core'
  if (exercise.movement === 'push') return 'push'
  if (exercise.movement === 'pull') return 'pull'
  return 'legs'
}
