import type { ExerciseGroup } from '../../types'

export type ExerciseCategory = 'lower' | 'upper' | 'core' | 'full_body'
export type MovementPattern = 'squat' | 'hinge' | 'push' | 'pull' | 'rotation' | 'carry' | 'locomotion'
export type IntensityType = 'strength' | 'power' | 'hypertrophy' | 'stability' | 'recovery'
export type EquipmentType =
  | 'barbell'
  | 'dumbbell'
  | 'bodyweight'
  | 'machine'
  | 'cable'
  | 'kettlebell'
  | 'medball'
  | 'bands'
  | 'trap_bar'
  | 'trx'
  | 'box'
  | 'ladder'
  | 'plate'
  | 'stability_ball'
export type ExperienceLevel = 'beginner' | 'intermediate' | 'advanced'
export type ExerciseRiskLevel = 'low' | 'medium' | 'high'
export type ExerciseFatigueCost = 'low' | 'medium' | 'high'

export interface ExerciseDefinition {
  id: string
  name: string
  category: ExerciseCategory
  movement: MovementPattern
  intensityType: IntensityType
  equipment: EquipmentType[]
  unilateral?: boolean
  tags: string[]
  description: string
  aliases?: string[]
  difficulty?: ExperienceLevel
  sportsTransfer?: string[]
  squashTransfer?: string[]
  riskLevel?: ExerciseRiskLevel
  fatigueCost?: ExerciseFatigueCost
}

export type StrengthExerciseRole = 'main_lift' | 'accessory' | 'trunk' | 'power'

export const STRENGTH_EXERCISE_LIBRARY: ExerciseDefinition[] = [
  {
    id: 'back_squat',
    name: 'Back squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'advanced', 'athletic_transfer', 'squash_specific'],
    description: 'Primary bilateral squat pattern for lower-body strength and force production.',
    aliases: ['Sentadilla', 'Barbell back squat'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['force_production', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'front_squat',
    name: 'Front squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'athletic_transfer', 'squash_specific'],
    description: 'Upright squat variation with more trunk demand and quad emphasis.',
    aliases: ['Sentadilla frontal', 'Barbell front squat'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['force_production', 'trunk_stiffness'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'kettlebell'],
    tags: ['lower_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Accessible squat option useful for volume, technique and home-gym sessions.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian split squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'gym', 'home_gym', 'squash_specific', 'lateral_strength'],
    description: 'Single-leg squat variation for unilateral strength, balance and trunk control.',
    aliases: ['Bulgarian split squat', 'Sentadilla bulgara'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['single_leg_strength', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'walking_lunge',
    name: 'Walking lunge',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'general_fitness', 'squash_specific'],
    description: 'Locomotion-based unilateral lower-body work with coordination and stability demand.',
    aliases: ['Zancadas', 'Lunges'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['court_lunge_capacity', 'single_leg_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian deadlift',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['lower_strength', 'hinge', 'gym', 'athletic_transfer', 'squash_specific'],
    description: 'Posterior-chain hinge emphasizing hamstrings, glutes and trunk stiffness.',
    aliases: ['RDL', 'Peso muerto rumano'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'cycling', 'squash'],
    squashTransfer: ['posterior_chain', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'advanced'],
    description: 'Heavy bilateral hinge for maximal force and whole-body strength.',
    difficulty: 'advanced',
    sportsTransfer: ['strength'],
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Trap bar deadlift',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['trap_bar', 'barbell'],
    tags: ['lower_strength', 'gym', 'athletic_transfer', 'general_fitness', 'squash_specific'],
    description: 'Lower-skill hinge with athletic transfer and slightly lower technical cost.',
    aliases: ['Trap bar DL', 'Hex bar deadlift'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['force_production', 'posterior_chain'],
    riskLevel: 'medium',
    fatigueCost: 'high',
  },
  {
    id: 'hip_thrust',
    name: 'Hip thrust',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'hypertrophy',
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    tags: ['lower_strength', 'glute_focus', 'gym', 'home_gym', 'athletic_transfer', 'squash_specific'],
    description: 'Hip-dominant exercise for glute strength and sprint or jump transfer.',
    aliases: ['Empuje de cadera'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['hip_extension', 'acceleration'],
    riskLevel: 'low',
    fatigueCost: 'medium',
  },
  {
    id: 'step_up',
    name: 'Step up',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'beginner_friendly', 'home_gym', 'athletic_transfer', 'squash_specific'],
    description: 'Single-leg pattern with clear transfer to stairs, running and court movement.',
    aliases: ['Step-up', 'Subida al cajon'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
    squashTransfer: ['single_leg_strength', 'court_lunge_capacity'],
    riskLevel: 'low',
    fatigueCost: 'medium',
  },
  {
    id: 'bench_press',
    name: 'Bench press',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['upper_strength', 'gym', 'compound'],
    description: 'Primary horizontal pressing lift for upper-body strength.',
    aliases: ['Press banca'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['upper_body_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline dumbbell press',
    category: 'upper',
    movement: 'push',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'home_gym'],
    description: 'Upper-body press with shoulder-friendly setup and moderate hypertrophy bias.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'overhead_press',
    name: 'Overhead press',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'gym', 'compound', 'athletic_transfer', 'squash_specific'],
    description: 'Vertical pressing pattern with high trunk stiffness and shoulder control demand.',
    aliases: ['Press hombro', 'Press militar'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'push_press',
    name: 'Push press',
    category: 'upper',
    movement: 'push',
    intensityType: 'power',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'power', 'gym', 'advanced', 'athletic_transfer'],
    description: 'Explosive vertical press with leg drive for power expression.',
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'pull_up',
    name: 'Pull up',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'compound', 'gym', 'home_gym', 'squash_specific'],
    description: 'Vertical pulling strength using bodyweight as load.',
    aliases: ['Dominadas'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['shoulder_resilience', 'upper_back_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'assisted_pull_up',
    name: 'Assisted pull up',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['machine', 'bands'],
    tags: ['upper_strength', 'beginner_friendly', 'gym', 'home_gym'],
    description: 'Accessible vertical pull variation for building pulling volume.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'bent_over_row',
    name: 'Bent over row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'gym', 'compound'],
    description: 'Horizontal pull with trunk demand and upper-back strength emphasis.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'chest_supported_row',
    name: 'Chest supported row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'machine'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'beginner_friendly'],
    description: 'Stable horizontal row that reduces lower-back fatigue.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat pulldown',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['machine', 'cable'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'beginner_friendly'],
    description: 'Controlled vertical pulling option for volume and shoulder-friendly work.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'pallof_press',
    name: 'Pallof press',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['cable', 'bands'],
    tags: ['core', 'stability', 'athletic_transfer', 'gym', 'home_gym', 'squash_specific', 'anti_rotation'],
    description: 'Anti-rotation trunk drill for bracing and force transfer.',
    aliases: ['Press Pallof', 'Anti-rotation press'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
    squashTransfer: ['anti_rotation', 'trunk_stiffness'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'dead_bug',
    name: 'Dead bug',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'beginner_friendly', 'home_gym', 'anti_extension'],
    description: 'Low-load trunk control drill with breathing and pelvic stability emphasis.',
    aliases: ['Bicho muerto'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness', 'squash'],
    squashTransfer: ['pelvic_control', 'trunk_stiffness'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'beginner_friendly', 'home_gym'],
    description: 'Isometric trunk stiffness exercise with simple dosage.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'side_plank',
    name: 'Side plank',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'unilateral', 'home_gym', 'squash_specific', 'lateral_stability'],
    description: 'Lateral trunk stability drill useful for running and rotational sports.',
    aliases: ['Plancha lateral'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
    squashTransfer: ['lateral_stability', 'anti_lateral_flexion'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'med_ball_rotational_throw',
    name: 'Med ball rotational throw',
    category: 'core',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['core', 'power', 'athletic_transfer', 'gym'],
    description: 'Explosive rotational power drill with strong transfer to court sports.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'cable_chop',
    name: 'Cable chop',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['cable', 'bands'],
    tags: ['core', 'rotation', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Rotational trunk pattern for controlled transfer across hips and shoulders.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
  },
  {
    id: 'farmer_carry',
    name: 'Farmer carry',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['dumbbell', 'kettlebell'],
    tags: ['core', 'carry', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Loaded carry for grip, trunk stiffness and gait integrity.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash', 'cycling'],
  },
  {
    id: 'box_jump',
    name: 'Box jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight', 'box'],
    tags: ['power', 'athletic_transfer', 'gym', 'squash_specific', 'jump_power'],
    description: 'Low-volume explosive jump for lower-body power expression.',
    aliases: ['Salto al cajon'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
    squashTransfer: ['vertical_power', 'landing_quality'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'jump_squat',
    name: 'Jump squat',
    category: 'full_body',
    movement: 'squat',
    intensityType: 'power',
    equipment: ['bodyweight', 'dumbbell'],
    tags: ['power', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Explosive squat pattern emphasizing rate of force development.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'med_ball_slam',
    name: 'Med ball slam',
    category: 'full_body',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Total-body explosive pattern with low eccentric cost.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'rotational_med_ball_throw',
    name: 'Rotational med ball throw',
    category: 'full_body',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Explosive rotational pattern for sport transfer and intent.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell swing',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['kettlebell'],
    tags: ['power', 'athletic_transfer', 'home_gym', 'gym'],
    description: 'Ballistic hinge pattern for hip speed and posterior-chain snap.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'clean',
    name: 'Clean',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'olympic_power', 'advanced', 'high_skill', 'athletic_transfer', 'squash_specific'],
    description: 'Olympic pull-to-catch pattern for full-body power and rate of force development.',
    aliases: ['Power clean', 'Cargada'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['rate_of_force_development', 'explosive_start'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'clean_high_pull',
    name: 'Clean high pull',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'olympic_power', 'advanced', 'high_skill', 'athletic_transfer', 'squash_specific'],
    description: 'Explosive Olympic pull variation without the catch, useful for power when technique allows.',
    aliases: ['High pull', 'Clean pull alto'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['rate_of_force_development', 'posterior_chain_power'],
    riskLevel: 'high',
    fatigueCost: 'medium',
  },
  {
    id: 'split_jerk',
    name: 'Split jerk',
    category: 'full_body',
    movement: 'push',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'olympic_power', 'advanced', 'high_skill', 'athletic_transfer', 'squash_specific'],
    description: 'Explosive overhead split pattern with high coordination and shoulder stability demands.',
    aliases: ['Jerk split', 'Envion split'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['split_stance_power', 'trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'barbell_jump_squat',
    name: 'Barbell jump squat',
    category: 'full_body',
    movement: 'squat',
    intensityType: 'power',
    equipment: ['barbell'],
    tags: ['power', 'jump_power', 'advanced', 'athletic_transfer', 'squash_specific'],
    description: 'Loaded jump squat for explosive lower-body intent with careful load control.',
    aliases: ['Jump squat con barra', 'BB jump squat'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['vertical_power', 'rate_of_force_development'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'bb_reverse_lunge',
    name: 'BB reverse lunge',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['barbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'squash_specific', 'court_lunge'],
    description: 'Loaded reverse lunge for deceleration, hip control and squash-specific lunge capacity.',
    aliases: ['Barbell reverse lunge', 'Reverse lunge con barra', 'Zancada atras con barra'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['court_lunge_capacity', 'deceleration', 'single_leg_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'bb_side_lunge',
    name: 'BB side lunge',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['barbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'squash_specific', 'lateral_strength', 'court_lunge'],
    description: 'Loaded lateral lunge for frontal-plane strength and wide-ball court positions.',
    aliases: ['BB side lunges', 'Barbell side lunge', 'Lateral lunge con barra', 'Zancada lateral con barra'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['lateral_strength', 'court_lunge_capacity', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'single_leg_hip_thrust',
    name: 'Single leg hip thrust',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight', 'dumbbell', 'barbell'],
    unilateral: true,
    tags: ['lower_strength', 'glute_focus', 'unilateral', 'athletic_transfer', 'squash_specific'],
    description: 'Unilateral hip extension pattern for glute strength with lower spinal cost.',
    aliases: ['SL hip thrust', 'Hip thrust una pierna'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['hip_extension', 'single_leg_strength'],
    riskLevel: 'low',
    fatigueCost: 'medium',
  },
  {
    id: 'z_press',
    name: 'Z Press',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'trunk_stability', 'gym', 'athletic_transfer', 'squash_specific'],
    description: 'Seated floor press variation that exposes trunk and overhead control limitations.',
    aliases: ['Z press', 'Press Z'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'mixed_grip_pull_up',
    name: 'Mixed grip pull up',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'compound', 'gym', 'squash_specific'],
    description: 'Pull-up variation that challenges grip and shoulder control asymmetrically.',
    aliases: ['Mixed grip pull-up', 'Dominada agarre mixto'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['grip_strength', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'weighted_pull_up',
    name: 'Weighted pull up',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight', 'plate', 'dumbbell'],
    tags: ['upper_strength', 'compound', 'gym', 'advanced', 'squash_specific'],
    description: 'Loaded vertical pull for maximal upper-body pulling strength.',
    aliases: ['Weighted pull-up', 'Dominada lastrada'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['grip_strength', 'upper_back_strength'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'trx_inverted_row',
    name: 'TRX inverted row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['trx', 'bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'squash_specific'],
    description: 'Suspension row with scalable difficulty for upper-back strength and shoulder control.',
    aliases: ['TRX row', 'Remo invertido TRX'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['upper_back_strength', 'shoulder_resilience'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'half_kneeling_row',
    name: 'Half kneeling row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['cable', 'bands', 'dumbbell'],
    tags: ['upper_strength', 'anti_rotation', 'athletic_transfer', 'squash_specific'],
    description: 'Row from half-kneeling stance to pair upper-back strength with pelvic and trunk control.',
    aliases: ['1:2 Kneeling Row', '1/2 Kneeling Row', 'Half-kneeling row', 'Remo medio arrodillado'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['anti_rotation', 'upper_back_strength'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'barbell_single_leg_inverted_row',
    name: 'Barbell single leg inverted row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['barbell', 'bodyweight'],
    unilateral: true,
    tags: ['upper_strength', 'core', 'athletic_transfer', 'squash_specific'],
    description: 'Single-leg inverted row under a bar that adds posterior-chain and trunk control demand.',
    aliases: ['BB single leg inverted row', 'Single leg inverted row'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['upper_back_strength', 'trunk_stiffness'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'broad_jump',
    name: 'Broad jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    tags: ['power', 'jump_power', 'athletic_transfer', 'squash_specific'],
    description: 'Horizontal jump for acceleration intent and landing quality.',
    aliases: ['Salto horizontal'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['horizontal_power', 'landing_quality'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'single_leg_broad_jump',
    name: 'Single leg broad jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    unilateral: true,
    tags: ['power', 'jump_power', 'unilateral', 'advanced', 'squash_specific'],
    description: 'Single-leg horizontal jump for unilateral power and controlled landings.',
    aliases: ['SL broad jump', 'Salto horizontal una pierna'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['single_leg_power', 'landing_quality'],
    riskLevel: 'high',
    fatigueCost: 'medium',
  },
  {
    id: 'drop_jump',
    name: 'Drop jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['box', 'bodyweight'],
    tags: ['power', 'reactive_stiffness', 'advanced', 'high_impact', 'squash_specific'],
    description: 'Low-contact reactive jump emphasizing stiffness and short ground contact.',
    aliases: ['Salto reactivo desde cajon'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['reactive_stiffness', 'split_step_quality'],
    riskLevel: 'high',
    fatigueCost: 'medium',
  },
  {
    id: 'depth_jump',
    name: 'Depth jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['box', 'bodyweight'],
    tags: ['power', 'reactive_stiffness', 'advanced', 'high_impact', 'squash_specific'],
    description: 'High-intensity plyometric drop and rebound jump for advanced athletes only.',
    aliases: ['Salto profundo'],
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['reactive_stiffness', 'explosive_reacceleration'],
    riskLevel: 'high',
    fatigueCost: 'high',
  },
  {
    id: 'half_kneeling_lateral_jump',
    name: 'Half kneeling lateral jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    unilateral: true,
    tags: ['power', 'lateral_power', 'athletic_transfer', 'squash_specific'],
    description: 'Lateral jump from half-kneeling to train hip snap and frontal-plane power.',
    aliases: ['Half-kneeling lateral jump', 'Salto lateral medio arrodillado'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['lateral_power', 'court_reacceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'lateral_skater_jumps',
    name: 'Lateral skater jumps',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    unilateral: true,
    tags: ['power', 'lateral_power', 'athletic_transfer', 'squash_specific'],
    description: 'Side-to-side bounds for lateral power, deceleration and reacceleration.',
    aliases: ['Skater jumps', 'Saltos patinador'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['lateral_power', 'deceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'alternating_step_up_jump',
    name: 'Alternating step up jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['box', 'bodyweight'],
    unilateral: true,
    tags: ['power', 'jump_power', 'athletic_transfer', 'squash_specific'],
    description: 'Alternating explosive step-up pattern for unilateral power and rhythm.',
    aliases: ['Step up jump alternado'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['single_leg_power', 'court_reacceleration'],
    riskLevel: 'medium',
    fatigueCost: 'medium',
  },
  {
    id: 'pogo_jumps',
    name: 'Pogo jumps',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    tags: ['power', 'reactive_stiffness', 'athletic_transfer', 'squash_specific'],
    description: 'Low-amplitude ankle stiffness jumps for split-step and footwork elasticity.',
    aliases: ['Pogos', 'Saltos pogo'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['reactive_stiffness', 'split_step_quality'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_front_1',
    name: 'Escalera Bipodal Frente Ej 1',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Forward two-foot ladder pattern for rhythm and low-cost footwork coordination.',
    aliases: ['Escalera bipodal frente 1', 'Ladder bipodal front 1'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'split_step_quality'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_front_2',
    name: 'Escalera Bipodal Frente Ej 2',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Second forward two-foot ladder pattern for coordination variation.',
    aliases: ['Escalera bipodal frente 2', 'Ladder bipodal front 2'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'split_step_quality'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_front_3',
    name: 'Escalera Bipodal Frente Ej 3',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Third forward two-foot ladder pattern to vary rhythm without adding heavy load.',
    aliases: ['Escalera bipodal frente 3', 'Ladder bipodal front 3'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'split_step_quality'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_coordinativo_front_2',
    name: 'Escalera Coordinativo Frente 2',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Forward coordination ladder pattern for rhythm changes and quick feet.',
    aliases: ['Escalera coordinativo frente 2', 'Ladder coordination front 2'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'court_reacceleration'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_coordinativo_front_4',
    name: 'Escalera Coordinativo Frente 4',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'squash_specific', 'beginner_friendly'],
    description: 'Fourth forward coordination ladder pattern for sharper foot placement.',
    aliases: ['Escalera coordinativo frente 4', 'Ladder coordination front 4'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'court_reacceleration'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_lateral_1',
    name: 'Escalera Bipodal Lateralizacion Ej 1',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'lateral_power', 'squash_specific', 'beginner_friendly'],
    description: 'Lateral two-foot ladder pattern for court-specific side movement coordination.',
    aliases: ['Escalera bipodal lateralizacion 1', 'Ladder bipodal lateral 1'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'lateral_movement'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'ladder_bipodal_lateral_3',
    name: 'Escalera Bipodal Lateralizacion Ej 3',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['ladder', 'bodyweight'],
    tags: ['court_footwork', 'coordination', 'lateral_power', 'squash_specific', 'beginner_friendly'],
    description: 'Third lateral two-foot ladder pattern for variation in low-fatigue footwork.',
    aliases: ['Escalera bipodal lateralizacion 3', 'Ladder bipodal lateral 3'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['footwork_rhythm', 'lateral_movement'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'copenhagen_side_plank',
    name: 'Copenhagen side plank',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight', 'box'],
    unilateral: true,
    tags: ['core', 'stability', 'lateral_stability', 'adductor_strength', 'squash_specific'],
    description: 'Side plank variation emphasizing adductor strength and lateral trunk stability.',
    aliases: ['Copenhagen plank', 'Plancha Copenhagen'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['adductor_strength', 'lateral_stability'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'side_plank_plate_press',
    name: 'Side plank + plate press',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['plate', 'bodyweight'],
    unilateral: true,
    tags: ['core', 'stability', 'lateral_stability', 'anti_rotation', 'squash_specific'],
    description: 'Side plank with plate press to challenge lateral stability and anti-rotation control.',
    aliases: ['Side plank plate press', 'Plancha lateral con press de disco'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['lateral_stability', 'anti_rotation'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'stability_ball_front_plank',
    name: 'Stability ball front plank',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['stability_ball', 'bodyweight'],
    tags: ['core', 'stability', 'anti_extension', 'squash_specific'],
    description: 'Front plank on stability ball for anti-extension and shoulder-trunk control.',
    aliases: ['Swiss ball plank', 'Plancha frontal fitball'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['trunk_stiffness', 'shoulder_resilience'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'lateral_band_walk',
    name: 'Lateral band walk',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'stability',
    equipment: ['bands'],
    tags: ['lower_strength', 'stability', 'lateral_strength', 'beginner_friendly', 'squash_specific'],
    description: 'Low-load lateral hip activation for knee tracking and court movement prep.',
    aliases: ['Monster walk lateral', 'Caminata lateral con banda'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
    squashTransfer: ['lateral_stability', 'hip_control'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'bird_dog_renegade_row',
    name: 'Bird dog renegade row',
    category: 'core',
    movement: 'pull',
    intensityType: 'stability',
    equipment: ['dumbbell'],
    unilateral: true,
    tags: ['core', 'upper_strength', 'anti_rotation', 'squash_specific'],
    description: 'Bird dog row variation for anti-rotation, shoulder control and contralateral stability.',
    aliases: ['Bird-dog renegade row', 'Remo renegado bird dog'],
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['anti_rotation', 'shoulder_resilience'],
    riskLevel: 'medium',
    fatigueCost: 'low',
  },
  {
    id: 'half_kneeling_diagonal_plate_chop',
    name: 'Half kneeling diagonal plate chop',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['plate'],
    tags: ['core', 'rotation', 'anti_rotation', 'athletic_transfer', 'squash_specific'],
    description: 'Half-kneeling diagonal chop with a plate for controlled rotational transfer.',
    aliases: ['Half-kneeling plate chop', 'Corte diagonal con disco medio arrodillado'],
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash'],
    squashTransfer: ['anti_rotation', 'controlled_rotation'],
    riskLevel: 'low',
    fatigueCost: 'low',
  },
  {
    id: 'bodyweight_squat',
    name: 'Bodyweight squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'recovery',
    equipment: ['bodyweight'],
    tags: ['beginner_friendly', 'home_gym', 'general_fitness', 'recovery'],
    description: 'Low-cost squat pattern for tissue prep, recovery or entry-level training.',
    difficulty: 'beginner',
    sportsTransfer: ['general_fitness'],
  },
  {
    id: 'push_up',
    name: 'Push up',
    category: 'upper',
    movement: 'push',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Accessible horizontal press for bodyweight strength and volume.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'glute_bridge',
    name: 'Glute bridge',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'recovery',
    equipment: ['bodyweight', 'bands', 'dumbbell'],
    tags: ['beginner_friendly', 'home_gym', 'recovery', 'athletic_transfer'],
    description: 'Low-load glute pattern for activation and recovery sessions.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'band_row',
    name: 'Band row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'recovery',
    equipment: ['bands'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'recovery'],
    description: 'Low-cost horizontal pulling option for recovery and home-gym work.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'split_squat',
    name: 'Split squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight', 'dumbbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'beginner_friendly', 'home_gym'],
    description: 'Accessible unilateral lower-body pattern with low setup complexity.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'inverted_row',
    name: 'Inverted row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Bodyweight horizontal pull with scalable difficulty.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
]

export function getStrengthExerciseRole(definition: ExerciseDefinition, index = 0): StrengthExerciseRole {
  if (definition.category === 'core') return 'trunk'
  if (definition.intensityType === 'power') return 'power'
  return index === 0 ? 'main_lift' : 'accessory'
}

export function normalizeStrengthExerciseKey(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
}

export function findStrengthExerciseByName(name: string): ExerciseDefinition | undefined {
  const normalized = normalizeStrengthExerciseKey(name)

  const exact = STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    normalizeStrengthExerciseKey(exercise.name) === normalized ||
    normalizeStrengthExerciseKey(exercise.id) === normalized,
  )
  if (exact) return exact

  const aliasExact = STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    exercise.aliases?.some((alias) => normalizeStrengthExerciseKey(alias) === normalized),
  )
  if (aliasExact) return aliasExact

  const aliasMap: Record<string, string> = {
    sentadilla: 'back_squat',
    sentadilla_frontal: 'front_squat',
    press_banca: 'bench_press',
    press_z: 'z_press',
    press_hombro: 'overhead_press',
    press_militar: 'overhead_press',
    remo_con_barra: 'bent_over_row',
    dominadas: 'pull_up',
    dominada_lastrada: 'weighted_pull_up',
    dominada_agarre_mixto: 'mixed_grip_pull_up',
    dominadas_asistidas: 'assisted_pull_up',
    peso_muerto: 'deadlift',
    peso_muerto_trap_bar: 'trap_bar_deadlift',
    peso_muerto_rumano: 'romanian_deadlift',
    rdl: 'romanian_deadlift',
    zancadas: 'walking_lunge',
    zancada_lateral_con_barra: 'bb_side_lunge',
    zancada_atras_con_barra: 'bb_reverse_lunge',
    core_rotacional: 'cable_chop',
    plancha: 'plank',
    plancha_lateral: 'side_plank',
    plancha_copenhagen: 'copenhagen_side_plank',
    puente_gluteo: 'glute_bridge',
    salto_al_cajon: 'box_jump',
    salto_horizontal: 'broad_jump',
    saltos_pogo: 'pogo_jumps',
  }

  const aliasId = aliasMap[normalized]
  if (aliasId) {
    return STRENGTH_EXERCISE_LIBRARY.find((exercise) => exercise.id === aliasId)
  }

  return STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    normalized.includes(normalizeStrengthExerciseKey(exercise.name)) ||
    normalizeStrengthExerciseKey(exercise.name).includes(normalized) ||
    exercise.aliases?.some((alias) =>
      normalized.includes(normalizeStrengthExerciseKey(alias)) ||
      normalizeStrengthExerciseKey(alias).includes(normalized),
    ),
  )
}

export function getExerciseGroupForDefinition(exercise: ExerciseDefinition): ExerciseGroup {
  if (exercise.tags.includes('olympic_power')) return 'olympic'
  if (exercise.category === 'core') return 'core'
  if (exercise.movement === 'push') return 'push'
  if (exercise.movement === 'pull') return 'pull'
  return 'legs'
}
