import type { ExerciseGroup } from '../../types'

export type ExerciseCategory = 'lower' | 'upper' | 'core' | 'full_body'
export type MovementPattern = 'squat' | 'hinge' | 'push' | 'pull' | 'rotation' | 'carry' | 'locomotion'
export type IntensityType = 'strength' | 'power' | 'hypertrophy' | 'stability' | 'recovery'
export type EquipmentType = 'barbell' | 'dumbbell' | 'bodyweight' | 'machine' | 'cable' | 'kettlebell' | 'medball' | 'bands'
export type ExperienceLevel = 'beginner' | 'intermediate' | 'advanced'

export interface ExerciseDefinition {
  id: string
  name: string
  category: ExerciseCategory
  movement: MovementPattern
  intensityType: IntensityType
  equipment: EquipmentType[]
  unilateral?: boolean
  tags: string[]
  description: string
  difficulty?: ExperienceLevel
  sportsTransfer?: string[]
}

export const STRENGTH_EXERCISE_LIBRARY: ExerciseDefinition[] = [
  {
    id: 'back_squat',
    name: 'Back squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'advanced', 'athletic_transfer'],
    description: 'Primary bilateral squat pattern for lower-body strength and force production.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
  },
  {
    id: 'front_squat',
    name: 'Front squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'athletic_transfer'],
    description: 'Upright squat variation with more trunk demand and quad emphasis.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'kettlebell'],
    tags: ['lower_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Accessible squat option useful for volume, technique and home-gym sessions.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian split squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Single-leg squat variation for unilateral strength, balance and trunk control.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
  },
  {
    id: 'walking_lunge',
    name: 'Walking lunge',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'athletic_transfer', 'general_fitness'],
    description: 'Locomotion-based unilateral lower-body work with coordination and stability demand.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian deadlift',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['lower_strength', 'hinge', 'gym', 'athletic_transfer'],
    description: 'Posterior-chain hinge emphasizing hamstrings, glutes and trunk stiffness.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'cycling', 'squash'],
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'compound', 'advanced'],
    description: 'Heavy bilateral hinge for maximal force and whole-body strength.',
    difficulty: 'advanced',
    sportsTransfer: ['strength'],
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Trap bar deadlift',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['lower_strength', 'gym', 'athletic_transfer', 'general_fitness'],
    description: 'Lower-skill hinge with athletic transfer and slightly lower technical cost.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
  },
  {
    id: 'hip_thrust',
    name: 'Hip thrust',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'hypertrophy',
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    tags: ['lower_strength', 'glute_focus', 'gym', 'home_gym', 'athletic_transfer'],
    description: 'Hip-dominant exercise for glute strength and sprint or jump transfer.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
  },
  {
    id: 'step_up',
    name: 'Step up',
    category: 'lower',
    movement: 'locomotion',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'bodyweight'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'beginner_friendly', 'home_gym', 'athletic_transfer'],
    description: 'Single-leg pattern with clear transfer to stairs, running and court movement.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'bench_press',
    name: 'Bench press',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell'],
    tags: ['upper_strength', 'gym', 'compound'],
    description: 'Primary horizontal pressing lift for upper-body strength.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength'],
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline dumbbell press',
    category: 'upper',
    movement: 'push',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'home_gym'],
    description: 'Upper-body press with shoulder-friendly setup and moderate hypertrophy bias.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'overhead_press',
    name: 'Overhead press',
    category: 'upper',
    movement: 'push',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'gym', 'compound', 'athletic_transfer'],
    description: 'Vertical pressing pattern with high trunk stiffness and shoulder control demand.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'push_press',
    name: 'Push press',
    category: 'upper',
    movement: 'push',
    intensityType: 'power',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'power', 'gym', 'advanced', 'athletic_transfer'],
    description: 'Explosive vertical press with leg drive for power expression.',
    difficulty: 'advanced',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'pull_up',
    name: 'Pull up',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'compound', 'gym', 'home_gym'],
    description: 'Vertical pulling strength using bodyweight as load.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'assisted_pull_up',
    name: 'Assisted pull up',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['machine', 'bands'],
    tags: ['upper_strength', 'beginner_friendly', 'gym', 'home_gym'],
    description: 'Accessible vertical pull variation for building pulling volume.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'bent_over_row',
    name: 'Bent over row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'strength',
    equipment: ['barbell', 'dumbbell'],
    tags: ['upper_strength', 'gym', 'compound'],
    description: 'Horizontal pull with trunk demand and upper-back strength emphasis.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'chest_supported_row',
    name: 'Chest supported row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['dumbbell', 'machine'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'beginner_friendly'],
    description: 'Stable horizontal row that reduces lower-back fatigue.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat pulldown',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['machine', 'cable'],
    tags: ['upper_strength', 'hypertrophy', 'gym', 'beginner_friendly'],
    description: 'Controlled vertical pulling option for volume and shoulder-friendly work.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'pallof_press',
    name: 'Pallof press',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['cable', 'bands'],
    tags: ['core', 'stability', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Anti-rotation trunk drill for bracing and force transfer.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running', 'cycling'],
  },
  {
    id: 'dead_bug',
    name: 'Dead bug',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'beginner_friendly', 'home_gym'],
    description: 'Low-load trunk control drill with breathing and pelvic stability emphasis.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'beginner_friendly', 'home_gym'],
    description: 'Isometric trunk stiffness exercise with simple dosage.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'side_plank',
    name: 'Side plank',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['bodyweight'],
    tags: ['core', 'stability', 'unilateral', 'home_gym'],
    description: 'Lateral trunk stability drill useful for running and rotational sports.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'med_ball_rotational_throw',
    name: 'Med ball rotational throw',
    category: 'core',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['core', 'power', 'athletic_transfer', 'gym'],
    description: 'Explosive rotational power drill with strong transfer to court sports.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'cable_chop',
    name: 'Cable chop',
    category: 'core',
    movement: 'rotation',
    intensityType: 'stability',
    equipment: ['cable', 'bands'],
    tags: ['core', 'rotation', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Rotational trunk pattern for controlled transfer across hips and shoulders.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'squash', 'running'],
  },
  {
    id: 'farmer_carry',
    name: 'Farmer carry',
    category: 'core',
    movement: 'carry',
    intensityType: 'stability',
    equipment: ['dumbbell', 'kettlebell'],
    tags: ['core', 'carry', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Loaded carry for grip, trunk stiffness and gait integrity.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash', 'cycling'],
  },
  {
    id: 'box_jump',
    name: 'Box jump',
    category: 'full_body',
    movement: 'locomotion',
    intensityType: 'power',
    equipment: ['bodyweight'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Low-volume explosive jump for lower-body power expression.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'jump_squat',
    name: 'Jump squat',
    category: 'full_body',
    movement: 'squat',
    intensityType: 'power',
    equipment: ['bodyweight', 'dumbbell'],
    tags: ['power', 'athletic_transfer', 'gym', 'home_gym'],
    description: 'Explosive squat pattern emphasizing rate of force development.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'med_ball_slam',
    name: 'Med ball slam',
    category: 'full_body',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Total-body explosive pattern with low eccentric cost.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'rotational_med_ball_throw',
    name: 'Rotational med ball throw',
    category: 'full_body',
    movement: 'rotation',
    intensityType: 'power',
    equipment: ['medball'],
    tags: ['power', 'athletic_transfer', 'gym'],
    description: 'Explosive rotational pattern for sport transfer and intent.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'squash'],
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell swing',
    category: 'full_body',
    movement: 'hinge',
    intensityType: 'power',
    equipment: ['kettlebell'],
    tags: ['power', 'athletic_transfer', 'home_gym', 'gym'],
    description: 'Ballistic hinge pattern for hip speed and posterior-chain snap.',
    difficulty: 'intermediate',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'bodyweight_squat',
    name: 'Bodyweight squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'recovery',
    equipment: ['bodyweight'],
    tags: ['beginner_friendly', 'home_gym', 'general_fitness', 'recovery'],
    description: 'Low-cost squat pattern for tissue prep, recovery or entry-level training.',
    difficulty: 'beginner',
    sportsTransfer: ['general_fitness'],
  },
  {
    id: 'push_up',
    name: 'Push up',
    category: 'upper',
    movement: 'push',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Accessible horizontal press for bodyweight strength and volume.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'glute_bridge',
    name: 'Glute bridge',
    category: 'lower',
    movement: 'hinge',
    intensityType: 'recovery',
    equipment: ['bodyweight', 'bands', 'dumbbell'],
    tags: ['beginner_friendly', 'home_gym', 'recovery', 'athletic_transfer'],
    description: 'Low-load glute pattern for activation and recovery sessions.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'band_row',
    name: 'Band row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'recovery',
    equipment: ['bands'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'recovery'],
    description: 'Low-cost horizontal pulling option for recovery and home-gym work.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
  {
    id: 'split_squat',
    name: 'Split squat',
    category: 'lower',
    movement: 'squat',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight', 'dumbbell'],
    unilateral: true,
    tags: ['lower_strength', 'unilateral', 'beginner_friendly', 'home_gym'],
    description: 'Accessible unilateral lower-body pattern with low setup complexity.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'running', 'squash'],
  },
  {
    id: 'inverted_row',
    name: 'Inverted row',
    category: 'upper',
    movement: 'pull',
    intensityType: 'hypertrophy',
    equipment: ['bodyweight'],
    tags: ['upper_strength', 'beginner_friendly', 'home_gym', 'general_fitness'],
    description: 'Bodyweight horizontal pull with scalable difficulty.',
    difficulty: 'beginner',
    sportsTransfer: ['strength', 'general_fitness'],
  },
]

export function normalizeStrengthExerciseKey(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
}

export function findStrengthExerciseByName(name: string): ExerciseDefinition | undefined {
  const normalized = normalizeStrengthExerciseKey(name)

  const exact = STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    normalizeStrengthExerciseKey(exercise.name) === normalized ||
    normalizeStrengthExerciseKey(exercise.id) === normalized,
  )
  if (exact) return exact

  const aliasMap: Record<string, string> = {
    sentadilla: 'back_squat',
    sentadilla_frontal: 'front_squat',
    press_banca: 'bench_press',
    press_hombro: 'overhead_press',
    press_militar: 'overhead_press',
    remo_con_barra: 'bent_over_row',
    dominadas: 'pull_up',
    dominadas_asistidas: 'assisted_pull_up',
    peso_muerto: 'deadlift',
    peso_muerto_rumano: 'romanian_deadlift',
    rdl: 'romanian_deadlift',
    zancadas: 'walking_lunge',
    core_rotacional: 'cable_chop',
    plancha: 'plank',
    plancha_lateral: 'side_plank',
    puente_gluteo: 'glute_bridge',
  }

  const aliasId = aliasMap[normalized]
  if (aliasId) {
    return STRENGTH_EXERCISE_LIBRARY.find((exercise) => exercise.id === aliasId)
  }

  return STRENGTH_EXERCISE_LIBRARY.find((exercise) =>
    normalized.includes(normalizeStrengthExerciseKey(exercise.name)) ||
    normalizeStrengthExerciseKey(exercise.name).includes(normalized),
  )
}

export function getExerciseGroupForDefinition(exercise: ExerciseDefinition): ExerciseGroup {
  if (exercise.category === 'core') return 'core'
  if (exercise.movement === 'push') return 'push'
  if (exercise.movement === 'pull') return 'pull'
  return 'legs'
}
