import type { SquashDrillDefinition } from './drillLibrary'

/** Content definitions are independent of selector scores and session modality. */
const drills: Array<[string, string, string, string, 'control' | 'technical' | 'shadows', 'solo' | 'partner', string, string]> = [
  ['wall_exit_control', 'Salida de pared lateral', 'wall_exit', 'drive', 'control', 'solo', 'Autolanzar cerca de la pared, separar la pelota con preparación corta y enviarla profunda. Alternar lados; descansar al perder equilibrio.', 'Pelota que sale limpia de pared y llega detrás del cuadro de servicio.'],
  ['back_wall_reset', 'Salida de pared de fondo', 'back_wall', 'drive', 'control', 'solo', 'Dejar pasar la pelota tras el bote en pared de fondo y sacar paralelo profundo. Reducir velocidad antes de aumentar dificultad.', 'Salida sin contacto de raqueta con pared y recuperación equilibrada.'],
  ['weak_side_targets', 'Precisión del lado débil', 'drive_patterns', 'drive', 'control', 'solo', 'Elegir derecha o revés según el objetivo declarado. Golpear hacia un objetivo de profundidad; registrar aciertos y total.', 'Bote detrás del cuadro de servicio, dentro del corredor elegido.'],
  ['beginner_racket_preparation', 'Preparación de raqueta inicial', 'preparation', 'drive', 'control', 'solo', 'Sin velocidad: preparar raqueta antes del bote, girar hombros y golpear desde una base estable. Empezar con autolanzamiento.', 'Preparación terminada antes del bote y contacto delante del cuerpo.'],
  ['transition_front_back', 'Transición fondo y zona delantera', 'transition_patterns', 'movement', 'technical', 'partner', 'Compañero alterna pelota profunda y corta predecible. Llegar con pasos de ajuste, golpear y recuperar la T sin cruzar trayectorias.', 'Recuperación de la T equilibrada antes del siguiente envío.'],
  ['reactive_ghosting_signal', 'Sombras reactivas con señal', 'ghosting_reactive', 'footwork', 'shadows', 'partner', 'Compañero señala una esquina al iniciar cada salida. Frenar con control y volver a la T; pausar completamente entre tandas.', 'Primera salida a la esquina correcta y frenado sin pasos de compensación.'],
  ['braking_reset', 'Frenado y recuperación a la T', 'braking', 'footwork', 'shadows', 'solo', 'Desplazarse sin pelota a dos esquinas, frenar con pasos cortos y volver estable. Aumentar alcance sólo si se mantiene control.', 'Llegada estable sin colapso de rodilla ni pérdida de equilibrio.'],
  ['pressure_eight_all', 'Decisiones desde ocho iguales', 'pressure_decision', 'decision', 'technical', 'partner', 'Simular rally desde 8-8 con prioridad a profundidad antes de atacar. Reiniciar tras cada punto y explicar la decisión; no es un partido competitivo.', 'Elección adecuada de pelota segura o ataque según posición rival.'],
  ['volley_read_choice', 'Lectura y decisión de volea', 'volley_patterns', 'volley', 'technical', 'partner', 'Compañero envía profundo o corto; volear sólo cuando hay tiempo y equilibrio, dejar pasar en caso contrario.', 'Decisión correcta antes del contacto y dirección controlada.'],
  ['drive_rest_reset', 'Paralelas con pausa completa', 'drive_patterns', 'drive', 'control', 'solo', 'Golpear una tanda corta de paralelas y pausar hasta recuperar respiración conversacional. Reiniciar si cae precisión.', 'Proporción de botes dentro del corredor marcado.'],
  ['feeder_front_court', 'Alimentación frontal con decisión', 'front_court_touch', 'drop', 'technical', 'partner', 'Alimentador entrega pelota cómoda a derecha o revés. Elegir toque corto o profundo según señal y recuperar posición.', 'Dirección coincidente con la señal, sin forzar un alcance inseguro.'],
  ['coach_volley_progression', 'Volea guiada por entrenador', 'volley_patterns', 'volley', 'technical', 'partner', 'Entrenador ajusta altura y velocidad. Bloquear volea con preparación corta; aumentar variabilidad tras cumplir el objetivo de precisión.', 'Contacto delante del cuerpo y llegada a la zona indicada.'],
  ['return_high_serve', 'Resto ante saque alto', 'serve_return', 'return', 'technical', 'partner', 'Compañero sirve alto con velocidad controlada. Leer el rebote, dejar espacio y devolver profundo por el lado declarado antes de recuperar la T.', 'Resto que supera el cuadro de servicio sin quedar atrapado contra la pared.'],
  ['return_body_serve', 'Resto ante saque al cuerpo', 'serve_return', 'return', 'technical', 'partner', 'Compañero sirve al cuerpo sin máxima velocidad. Crear espacio con pasos cortos, decidir derecha o revés y dirigir profundo. Pausar y corregir posición tras cada tanda.', 'Contacto con espacio suficiente y resto profundo hacia la zona elegida.'],
  ['return_fast_serve', 'Resto ante saque rápido', 'serve_return', 'return', 'technical', 'partner', 'Comenzar con saque de velocidad cómoda; preparar raqueta temprano y bloquear profundo. El compañero aumenta velocidad sólo si se mantiene la zona objetivo.', 'Lectura temprana y devolución profunda sin balanceo apresurado.'],
  ['defend_neutralize_attack', 'Defender, neutralizar y atacar', 'transition_patterns', 'decision', 'technical', 'partner', 'Compañero inicia profundo: defender con globo, recuperar posición y neutralizar con largo. Atacar sólo una pelota corta con equilibrio. Reiniciar la secuencia tras la decisión.', 'Ataque elegido únicamente después de recuperar posición y recibir una pelota favorable.'],
]

export const SQUASH_CATALOG_EXPANSION: SquashDrillDefinition[] = drills.map(([id, name, family, focus, sessionKind, executionMode, description, criterion]) => ({
  id, name, technicalFamily: family, category: sessionKind === 'shadows' ? 'physical' : 'technical',
  sessionKind, executionMode, focus: [focus], intensity: 'low', tags: [focus, 'quality', 'base', 'build', 'peak', 'taper', ...(executionMode === 'solo' ? ['solo'] : [])],
  description: `Objetivo: ${criterion} Ejecución: ${description} Clave: priorizar precisión y control antes de aumentar velocidad.`, progressionLevel: 1, intent: 'consistency', phaseAppropriate: ['base', 'build', 'peak', 'taper', 'transition'],
  successCriterion: criterion, regression: 'Reducir velocidad y variabilidad, usar una sola dirección y aumentar la pausa.',
  requirements: { court: sessionKind !== 'shadows', equipment: sessionKind === 'shadows' ? [] : ['racket', 'ball'],
    feeder: id === 'feeder_front_court', coach: id === 'coach_volley_progression' },
}))
